---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-mosquitto-data
  labels:
    app: mosquitto
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-mosquitto-data
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:mosquitto-data
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-mosquitto-data
  labels:
    app: mosquitto
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-mosquitto-data

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mqtt-passwd
spec:
  encryptedData:
    passwd: AgCF9GgaUKD/UsHs7qb3i7QvhjdwgYZUkypURFmrf6Da+O1Y1VvXoVnpFAZr6WEF/rL25XLVoS3r+ExWB0xq5PeqNjx5jlm3H8L4iAVqd2wyd8OqR3zSsbn/gv6dOLmV/8zWhzvIxWaZ9hx7DmEtDbfkEOic/nfMqsVYgXuGh3qV7+2tZ9Xrae3GRZVGks+zYRIIh/dcR8aO/hhJmEea0EAdTQzwzLurZR66LGj3HGaxmDl9jI9Q0KT7kPGXpbD5agIxIoRvysPN84cnEV1tF4C/Wn64ia4m2FKPa4zxZgjkOD1/8iGI0/lOv07YSy0n/p8rfkdMAA+demwqnd0WyJhKzR1gGcuehU6k38AYz19ycGPvux/8jVN4nKXqwNbEX5AhLh2EnRi7eb12tzrNWoAnRS79b4cup9zzNKq2dusARHlzw1pxPW3I2U0M/J9aWmkOpKgyg1QtoASQg7lvXsmvOLzC3CAhiHrezJ13d3wriz0MQ39iyn49iJhsbwiQhsEFwKfUVM/cU/lqGBnVjxR2opuliyVJ9z2da7jj0DnnrJxizo/WfSJAy+HNO8Q8dO7PdW5CKGlMcMJQlRuZn5uR2De3vOo73Vm0Jv+7+EyRokkSHHdTgF3mjbEEBuh/4QKT5WpCg2oYzASVMUK4kWC4kEmwtv6N2ibmGD0KcJ+skoqzf6/7M3s67zwG2wV6gHjM12P4nXdVpaQOCK3k9oXx7Q7KZ4JEMZqYrIp0xKuDSNxlA+bjoB/jhdB9SE+z1J1HolXoR0duj8J+Y5cRkO7FfrzxGtG++2DUxxtgUDSD+Ub0P72sDO/PbsCKMt9BU+R6GEoRhR7W/6LkmmVvf4hqbcTphlzCUW1c
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mqtt-passwd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-configmap
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/config/passwd
    persistence true
    persistence_location /mosquitto/data
    autosave_interval 1800

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: "docker.io/eclipse-mosquitto:latest"
          imagePullPolicy: Always
          resources: {}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: mqtt-websocket
              containerPort: 9001
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          startupProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /mosquitto/data
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: passwd
              mountPath: /mosquitto/config/passwd
              subPath: passwd
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-iscsi-mosquitto-data
        - name: config
          configMap:
            name: mosquitto-configmap
        - name: passwd
          secret:
            secretName: mqtt-passwd

---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto
  namespace: home-automation
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  type: ClusterIP
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
    - name: mqtt-websocket
      protocol: TCP
      port: 9001
      targetPort: mqtt-websocket

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mqtt-websocket
  labels:
    app: mosquitto
spec:
  ingressClassName: nginx-private
  rules:
    - host: mqtt.lan.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mosquitto
                port:
                  name: mqtt-websocket
