apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: 82f7a7e2fa3c6ef0a0459243c6ab4fb238c4afc5

labels:
- includeSelectors: true
  pairs:
    storage: truenas
