apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: 25d81aedbe9ed9e7258abb0eca4324510ea0236a

labels:
- includeSelectors: true
  pairs:
    storage: truenas
