apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: da762144bb3b4a01da4bbf65a7b0585ca410ff11

labels:
- includeSelectors: true
  pairs:
    storage: truenas
