apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/theautomation/home-assistant
  newTag: 3255ca952f3eb4cdc5ac3176a73d829f670e5f88

commonLabels:
  storage: truenas
