apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: bab656f4bf56761e262a78c07927405a8605bcad

labels:
- includeSelectors: true
  pairs:
    storage: truenas
