apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: 635f19a3b8f9c7f576ca097e8e2badd09e81364f

labels:
- includeSelectors: true
  pairs:
    storage: truenas
