apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/home-assistant
  newTag: bd9a1c92c151d8ff678c9232ed949dfc8eea9a69

labels:
- includeSelectors: true
  pairs:
    storage: truenas
