apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/theautomation/home-assistant
  newTag: 82750508792e033d40cb3705883d6d073d1c8e32

commonLabels:
  storage: truenas
