apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/theautomation/home-assistant
  newTag: a24aa93905edbd323a58c0b27344fdc2d2bebe15

commonLabels:
  storage: truenas
