apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: democratic-csi

commonLabels:
  storage: truenas

patches:
  - path: patch_deamonset_csi-manual-democratic-csi-node.yaml
