apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smbcredentials-coen
  labels:
    storage: truenas
$patch: replace
spec:
  encryptedData:
    mount_flags: AgDFrOEGwlTitusW7/vf6VLT3+X2AZxV++td5dNYbJLRIa1UfPJdjEeO8jm3nbZKuefAZttpJGvpdaAMo3Z2c+1Ky+FfLBlrRNJ2WxnaCvcuZsq4zXcQabai/Yoh/NCQERLWz+9JoGN5KbytYKoDzGVvW40JleFrAKYP9FMEUEpwEPR9kydoTESg0G8jqNFjXKv2aNPG6yoSkAqry8jORRx6sR7Or+4tHTupaPJJcyXpRMX+okOABkqnbUn5fARwYCPhytKob1GGEqiP7Rp+qrLzG+v8H8QiZ14WflCsscaPhHpkV24W61ktQIEblbCHZmPrm+CsB6jqrql1ArIOdsa/uJnxXr9On3f7mNDsXUza7GfIgQmB3JiNEmzYxVF0IrePyRcYzBvCIXs0g8P9cBLVqFu9cfxh08lbnZIyt8O4z7CZgWSnVhOWih1J5pgMnk2PATtLgQAFtl7R7fKRlZzbGBaC/FBLoozhsUXSExkEwFBpXiuTPHKwmhYB6DH3jfNGKDtUuxAQcGMvCctsoDJBJqtx7olGnfwlLtzLdNlNuARmnfKlNhj2x1PITf/0KyD+AIW/p775O2bHoX31V930FOdv9HJTjmSAfGS1OshfeMzd9kC0penjNRNQIxUzd0z5akPpIBiTA0vVK5lnUSRMOK6fVH9Bt3iXJgEvjikaZvtdoftUVmL225T6JnOS+aIu2EimB5vDfMC7hoCi/ZTJiGUzc6SeH04cfXI52D3LmG7EYtXHRQ==
  template:
    metadata:
      name: smbcredentials-coen