apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/is-it-dark
  newTag: 68f62b68252f6968e41ab07e8c4b392fbc4530cf
