apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/is-it-dark
  newTag: 36b21467eef1b93e3bdcd00dc042e596a46853e3
