---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-influxdb-data
  labels:
    app: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-influxdb-data
    volumeAttributes:
      portal: storage-server-lagg.lan.theautomation.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:influxdb-data
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: influxdb-auth
spec:
  encryptedData:
    admin-password: AgCYiNlE9IF0RCQ5RXWjiebJ7HJIasqFGBdX4Z5JnMwTm5z8RPg/RULyhVdBgQ6T6F2dm6K5IcQdEKlV/Bqj1o7X0Z86fAfvL+InX+ERfXLkyQGfHAjd5uiAQd7PnowNN+FVL4a5QnTnnO9Dug6XjgQdb2wXsyDV3+g+lXDoPcALDSwD68jfREGc2n/Oiv+WRz9Xkkiflndvx4M9BIlzK042Xzgl6ECjh3qjHpM0AzaUKllAG7zqcyae8E5EIDVPhHrksvFBqnit8mX102yW/xxpgQjkBbmXdweeXjGc6tuB2bajPv+w6IEFdySsRPTMdZY7eb1svdfdo19xWLTgqQaqNV1FXNmPBksANaSIkOFfwfLh5ouRGyI9bGNad9sptPa3qMm+gfzug22GMWyNW6o/snDYePNFDeioICSYcqjr8esHDGTf3Ww11HVcve46hlIkWrX+bUuw/VPOXAT3eTjdgn2t40/YOPNqUy3cwo0BFNXjqoEmb/adr5e/KMj05UCiAiZxcc2/okDNYbBHJYmJMUt8WwmXBsrNzyIjePYsudkdJONVQBvzA1P25T03mZwSKBGQ+nOjxaInzQYgjCw97B/jTumzh1sLBfEG0ww8dvyepcLEru8RcyfmNBd3Ex0yTa8qW5lpgsIcPAgo14wGxLGp4GbRfamks9q/q2rKBrwCjHt5bwNJbz9cjLlaNiAQYX0mfRgAkzxDS9sni81OVK8uqMqipYcOUeb42OCWLbyLXgNYz+Pcy5+O8Q==
    admin-token: AgBkqFPxqmhzPCp+fnQxqAjGTR6bS1V6sS0IdGblySTUk6vINp9qlFdX3KmYJRYgwzeZiWIrw34agfkQhWELOx+1yzDBrw/pwAGV2cgarSzzhKZ9ZRg+Cd4izT9sBM1MS8GFathshBNLdPAvszWSfMqDf0zbp+dz88OrZSHnJAjqVPDajlWXQhy0m3M0Kii9tGW4Q8rZ7A8OnWpXZvopVy7wSsh+HVa8yqULbyJNuwMiUPWfqMkLMi3xJ7bAKSHkE3hO9zcwKJnOD80iIZgMwg9c2/xBxCRCIztpQhxbEJgjeYh35RlykhldilpAxE1kvGF+ef4DquuRegnRRRo/04sZEVa8kq7ZyDMLeJ5nO8L9Vuj8hedKuSDRT7O1VNURz1rlcOKBnEtrXJx/KZHNnDTVQtQQBeESBvN0fkCTVVpivMNvAxbXY2yXVvbLplOG5v9D4XBM4L6I9Q+kN/QUysg1nKrE9hk3V0DsnvW8ksY0wM5sH4ukM/Ub7lKTVocVnl0+sVUBTrRknVlfeTPlna+y0eo5nueo3VbEru0KgRxGd6haYuj6mjSlsH819LCRjCA61qa0hyWJnczXf0s4xu9sysxq9J8CV9XxCcGnbPzuajRocGt8B9LWILrLMXEGeLuM1S3a6pa3ap+JLjvBI1DVBIfh4E41Oijb5IH8SUqN0HKxfPpNQoRz2x1gukMlW9Y3RNd4WceUXdHx+Bo4D2MZcpI09aRL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        app: influxdb
      name: influxdb-auth

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: influxdb
      containers:
        - name: influxdb
          image: "influxdb:2.7.4-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: admin
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-password
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: home
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: home-assistant
            - name: DOCKER_INFLUXDB_INIT_RETENTION
              value: 0s
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: admin-token
            - name: INFLUXD_BOLT_PATH
              value: /var/lib/influxdb2/influxd.bolt
            - name: INFLUXD_ENGINE_PATH
              value: /var/lib/influxdb2
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: influxdb
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        selector:
          matchLabels:
            app: influxdb
        accessModes:
          - "ReadWriteOnce"
        storageClassName: freenas-iscsi-manual-csi
        resources:
          requests:
            storage: "8Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ingressClassName: nginx-private
  rules:
    - host: influxdb.lan.theautomation.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: influxdb
                port:
                  name: http
