---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key-secret
  namespace: hermes
spec:
  encryptedData:
    api-token: AgBRqJnQEzagcWMN3zioYwg8PcyJp7PeYywIhEpEb7ea6L/fDRz1nchrL4g5l/6xLCShtOCcoZCobzaUmwp8iRb0bhRvSWqMDvwNBtf/qF2jzUJD4KAZv4F3y0Pnv4B2ZrN4N3Wdq5kXfLoEnl+pnIbs9ZRlDPFfZMESruV/XeFMumbEb47vOEzMbZz/eeQ+Yu7GcdPbAmvVhn/BHg2VK1eNrF6NLeQPQS5lPnUId9EoXIziU8FHLgXrsLcB4D9iGL+IqLxp1gHalIjVqal6nyn6o5NryjKf/ctGCPErSl3qTDLtY3wiY1kOgfgPFTHwIc+oXBgxHab1qhsmCFF3Lxdls9mTK4YwK8Ei1FG1aRtUgBOfBRU+jK2SABxMExS1Fbj64wtanBKYw/rDgtKH0XeOVS/UuoblhbeyMjX7P2CfwNJo0aPvP5W/63Ne2KTEMMO3Fzc66UmvjLC8CQOVJ3QAQ7iE9se8D0ywotVIVqDiTiK2oWjRYqcyT09koAsLgFEGOWCzVKUDOSMM33tH6zZGvnyLzkIylIOa9TRjIJr0hZxt2s7opehgAOOJVQZd3s8lvyHWvxh/F9Qg9XlG/TckGJZ1Gm7iumchD+3oRGlpDyFt5jdOdGohP3BO1kjgOGplfhu31FD7u/l626/zmJwnWwd6+uELM4RAY5TCebGlEETnwxj4J176zs3JmnJV/hWvkXXOmJN64FTP4wGtLoIB+9K9MaYhBoEPsrcyPAsx4w6e82aTbLMrfkhBwk2IL6Ka4hHgeN+a8U8CseGOYyOXRL7d7sFQnzXgj4UIUqpT5q83Jk/cJ0MQxS4nJ+08WisDPhKFJ+Co2NBpiyehBsqnevznKt+HURph9L5FgFTG/MUbgPJti2Xho0FZqI9SP2k25UsWf438UTEi8HuUbFTSDAY40w==
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key-secret
      namespace: hermes
