---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: tools

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.106.4
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.106.4
