---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ipaddresspool

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-lan-ips
spec:
  addresses:
    - 10.0.100.240/32 # ingress-controller
    - 10.0.100.241/32 # cups
    - 10.0.100.242/32 # omada controller
    - 10.0.100.243/32 # jellyfin

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-lan-ips
spec:
  addresses:
    - 10.0.100.250/32
