---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-lan-ips
spec:
  addresses:
    - 10.33.33.100/32 # private ingress-controller
    - 10.0.100.241/32 # jellyfin
    - 10.0.100.242/32 # tplink-omada-controller
  avoidBuggyIPs: true

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-lan-ips
spec:
  addresses:
    - 10.33.33.200/32 # public ingress-controller
  avoidBuggyIPs: true