---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-lan-ips
spec:
  addresses:
    - 10.33.33.100/32 # private ingress-controller
    - 10.0.100.241/32 # jellyfin
    - 10.0.100.242/32 # tplink-omada-controller
    - 10.0.100.243/32 # home-assistant coiot
    - 10.0.100.244/32 # syncthing
  avoidBuggyIPs: true

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-lan-ips
spec:
  addresses:
    - 10.33.33.200/32 # public ingress-controller
    - 10.33.33.201/32 # temp counterstrike
  avoidBuggyIPs: true
