---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - ../base
  - bgpadvertisement.yaml
  - bgppeer.yaml
  - ipaddresspool.yaml

patches:
  - path: patch_deamonset_speaker.yaml
