---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation

images:
  - name: ghcr.io/music-assistant/server
    newTag: beta

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
