---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key-secret
  namespace: tools
spec:
  encryptedData:
    api-token: AgA/m34zFF5rq6vFQWh+cNlp01fo1xnEwXD82XOSo/Wzp8PkG9EpRLC064iYFfUXMC8qOyuXJMehCjaxRHzjImnbXf6pKNx0pDX9f0J5w97dsABFAAklkKOULC2sBBEuT6gJiH2kBY+p3NGKUWxi6z/06QnHXOxC7tBcOcG+kx3MQDPoAuCanmFDSCQVYDL8ddW0jh55Q5RCkbNzVwruih+T1vkPwl6xuvk7iAfpc2bLlZSUj+vm7F1rA8LhzIhinYIKDBlAgWJJ9KRPNe+X3Ms+1PR2OIrEEahsbP0O674O3YI5GFgr46siOCteW8wkElvoOkAW/HrEV+0eAYZvj3Td+SovqmjJZ8ro8z4BPos8tQzKEI21xbpPlU1D78pFVSrIQs7sf9I96WJs5feEx/QGOYjIMShmd0U9TYiJ66xxAWwKJ9IOHXNm+/TA+WAWRXaEo7OY+T5k/yFUomcSiKV+xz0FhcX9Tdm7WyFlXKhsJ2NTyRfbSU1Yz9rStFYKQVz3U52RIeFkvow/yiVfGfaRgn1Muqoqnvqi2ILJcEetmvczkJ005DSD5A2p4JtoHRI1tBwhxr9S89g7I31eMPZTF2HIHhucrkonaTRT1xWPl41HI6BQC9RsW4ss+8UQqTWXFAOjomncAkb6iU3aFRuQES8wvwJd08i59HSBkq3Hs7yggsSjq3tn3pXovr0lBn/j9wnzg0YxmEprYD2FORBANfdW5SMC9gDFqWx3xFsBtMZVoOKycQQfjDm3Y2ECCrJy1iTfDsUo8Hui2xMHhxaFtJH9rl0x4PHwRyw3AiIy8ltvdQZeEuCbi8z12JMT8AQAq2yw+E5DljlE1FoCAXHzbN+kgZVJzTDbT8cqO6gReJXeKVmT4VBvO2ZJq1DQe36sbrT0yXJcK7DYWXhrZ+kOsNnoOg==
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key-secret
      namespace: tools
