apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation

commonLabels:
  storage: truenas

patches:
  - path: patch_deployment_zwavejs2mqtt-us.yaml
