---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwavejs2mqtt-us
spec:
  template:
    spec:
      tolerations:
        - key: "machine_type"
          operator: "Equal"
          value: "odroid"
          effect: "NoSchedule"
      nodeSelector:
        feature.node.kubernetes.io/usb-02_0658_0200.present: "true"
