---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-frigate-config
  labels:
    app: frigate
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-frigate-config
    volumeAttributes:
      portal: truenas-master.lan.theautomation.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:frigate-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-frigate-media
  labels:
    app: frigate
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-frigate-media
    volumeAttributes:
      server: truenas-master.lan.theautomation.nl
      share: /mnt/ssd/containers/k8s/frigate-media
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-frigate-config
  labels:
    app: frigate
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-frigate-config

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-frigate-media
  namespace: home-automation
  labels:
    app: frigate
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nfs-frigate-media

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: frigate-secrets
spec:
  encryptedData:
    FRIGATE_CAM01_RTSP_PASSWORD: AgDoWK1xS72IQRQZvPOlVGoLkkHg38rOeGzoYDtU4RZkNtpLXpbYpemQ9NiXs32W8zJJq7Z15Etq3nh9fPIu8wxC6cq5hjVWpyiD+Ww5/9KHn/2ORnZM8qheahA/I9sdi8pp4QQGdCnLSJUspLxqGustJducrVkx0ipOaVA9FPydoCQjmMPbzqIpv8abs104R2Uco7qXKAeKYbcWE8GNI0VCFOe841ZbftPcZFf899IiRc0vyW+pfgpJlMtPrSqPF4JPrFcc++hiSrWZW9erfZczB4bYgR4/NfX2pTK38TBkGQIAiG7eeqKLGmxlWX3msizuyADAMU5ylkh1KvtUmjf3oFVZWs04wqKtlKRhJNgNy7y2A58TEd7jz1vOdScwc2CMDmR9RBMqDWW9GNafjB5CaLB6RcHQ4V1xGEOx8yZGJPlPgaXII/6wMdAxnsa9SkQg/2tX39mRL9BRc7y+APe0F8VG6+diqvnhfTVrsHOd1zciSLzx6ilO84Mbvf3JUDYGbexsqA7SvUShyTQ/IE17BUeGXL4nqpKQFrCLBF3/OpcWQfXNqtjpLj5NkUXz8XL48wE0FFitLv8gqjtb80ri+eeURhtkdoHYIquT6bOCopsk5TUn/jLma85euoCvflwbPIH0QDxvEhV2teDefj7/fOSzMjPYhsFH1qO3xrZdxeVDl3AgFOm79bFlGka1hbu+UgkAldeV2Q==
    FRIGATE_CAM01_RTSP_USER: AgAeGVQt7QI77iEDclk7LRbxp8FS+D61gIC7QwW8dgb7kiGoHXCBQkOK2IWoEBRJS1ThL8OsxqDS5m+HAw90vNeykMCwpZwknnVbtR+bArKF6yIybk+3daXEvayTvvJ08k5p7keuawkNy3IzSU018+ZGOv8e3o/ZphMgYZEdp3xXuK/F0W1GgisgbI7c7gz2vt6K/DRoU1t31OiKszv/lvMP2uz+45c7HgjnqqYh/1+w4U1BbvGPe5NmEQM5qSvpv4V9gnbsLkvRhw2VcvbgDkkG23LdHffFQP6ctPxdiiiRVpI9kVGd66zHTJ38YYCXx08XBdViKRL9kdwsR4Pf0IypNjE44/l/s6kP6xYMaKJQHWpqqW9MhkBixCmelyKRy2eMJrI6Yx9HYlsdPFOu2tlLOp/MM/Lgj2LnFWf2szeNTch06hAzCKFED+HEskZX3Zr8QQzhWOpqBsXtlWgvLpvZsXrfS3voZ0n4kVCUJIXcv/wWsHYsJlKqbhiZoedHEXyaNAK59c41UHEpfQyTktjhP10mRKuTF5uSiR/N7PtgdGxSrmG2BbWfdsO+XO1dKmvlXisFRO+1AgjbosmXtcaITFyZ2hoRcOP/4GgnVKOPq8HhSMc+tAocCMLKe8uIqy5slJQMBZdLkdluPku3U1qoZmJhEjk5W3KdjT53VS3tc2iG/lBIZ20WVWyniOSywlm+iFm3Eg==
    FRIGATE_CAM02_RTSP_PASSWORD: AgDW8k+EbURhswGkr/MoxDkxn99MzfyBlebVxXpL2f2C9lBMB3m1tnWycq0NuSTrjJYj3UOtkIiMFCz+hRYOvubqe1S9Wb0t8JeZrpvjJtSE7lc1PzBGwLCElrhShY4R5BfS/LW4jC/k5UIwM+epytql2F1aBrWtRMIqLlujI+rtvyWMNNgL458JZSyt2MaSaLOrd5zwpQLISTtMlKxTlsVzZUAV5MEM1DXmbpSBMyMDcKCI0ENkzFPAbwB59Z3rkQPPe/sk5G4VODJpXDa/mMdpTFYmJWWaXzEk9F5OsGgj7+pHFPQtEh7YxF7oheeeE40Ut7VwFDuEhjcwtJ8IggtdKd5LPC76dNbLawICCUSd674pXYAM4tkQM76h8FQtQsCDrKAdUMPi+cWCHPcgg8GVxR+YgsgUn0f0ZpkKeRWYLLg4udlCJkRQtBJTcFysafQRx+sb6RUm8eWna3NPxTM/ieGYi5W8W7Tdx1N/MBz5D3hrhSqfMxiJq4FOWJN8Vk8Jk4flB+NBiM3q/uMf4U0CuNTTwEYx5OP5F/CISH4nC+k8iQbuyqTtLHXcPGIuUwVePfujsQAu+twTgN167Xbl9KobDp7YKMCAigloKMhWRBLLHOVUdUXN8usdRAG8BJX/BntzO6epxDDTcNHW40UyWVQQrO/0AauFmFxs2FDmDqF+YxxV4o9gD5fyabU+5AUSR46degXaNUs3a/E=
    FRIGATE_CAM02_RTSP_USER: AgAZLxQ8DjkQQO08in5R+TRFebzzytZjvWA3cn3B1+nsNcapa8JxaqIEQctmle8Zzf+f9qiQG52rbZ5vaF7pSZP8KmTr9trie/0OwhivqQ23Qxz0Uave0hosw94vNEyqj9R4ggTgKTMxrVPYXKvth4Q7vTBrq5TbXxiNtnzhv6oGUEbVJiT+1eHxj2axmkz3Hx08VK0ch1CArBFXp4YsL8QEwLR4La22+nuspsrKc9K1+04dDgHxSQOTXxTRe8faq0QDmf2CFqq2r/YyZZusFnyi6JV8F4UKB+0UIrfRfexoP5NUQG1jn3Pb4G6HGwf3lOMT9gssLgPXdHqAsQJpU/ePZFTlOqHHVs4jtgv9tezp9lvQ+Y0Jk67M0zcrufT5cp3XtS64wVrL3+iAV4ymlcDnzYIVsckooSVi/afTrtchRnAMUZGejYrS9EiVpPyFdplkqmmR9tk22hbgSHJyNdbFYY26rb4nfr8bFZfd1CPGkZq38uBdQfbDsCBUgRk+GyzKMMzzEigmYFCSA/uBafAyYmJ4EMPvkErOyCHq+boHJmCSwlRDvToqkDGsAyK1iAfNoyw3BvyJUpF6cwEXklHyo22q4aw7AnhRLa5/oOJoTeB06hok3OIfZGWxFo0Gk/60CGsNaEBfqUPhduEn7TI1KdhdvkN8R2hEGowrSabN+D0zEQBySsHcmf1pbWYsASa+fcVXkDt9QdjshM4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: vaultwarden
      name: frigate-secrets
    type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  labels:
    app: frigate
data:
  config.yml: |
    tls:
      enabled: false

    auth:
      enabled: True
      reset_admin_password: False

    mqtt:
      host: mosquitto.home-automation.svc.cluster.local
      port: 1883
      topic_prefix: frigate
      client_id: frigate
      stats_interval: 60

    go2rtc:
      streams:
        ipcam-01: rtsp://{FRIGATE_CAM01_RTSP_USER}:{FRIGATE_CAM01_RTSP_PASSWORD}@ipcam-01.lan.theautomation.nl:554/cam/realmonitor?channel=1&subtype=0
        ipcam-02: rtsp://{FRIGATE_CAM02_RTSP_USER}:{FRIGATE_CAM02_RTSP_PASSWORD}@ipcam-02.lan.theautomation.nl/live0

    cameras:
      backyard:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/ipcam-01
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        objects:
          track:
            - person
            - cat
            - dog
        detect:
          width: 1280
          height: 720
          fps: 5
        record:
          enabled: True
          retain:
            days: 3
            mode: all
          events:
            retain:
              default: 14
              mode: motion
        motion:
          mask:
            - 0.179,0.49,0.304,0.439,0.525,0.442,0.519,0.671,0.624,0.691,0.637,0.588,0.66,0.546,0.686,0.553,0.711,0.715,0.708,0.789,0.734,0.844,0.77,0.847,0.671,1,0.977,0.995,1,0,0.266,0,0.214,0.149,0.159,0.32

      baby:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/ipcam-02
              input_args: preset-rtsp-restream
              roles:
                - detect
                - record
        objects:
          track:
            - person
        detect:
          width: 1280
          height: 720
          fps: 5
        record:
          enabled: True
          retain:
            days: 3
            mode: all
          events:
            retain:
              default: 14
              mode: motion
        motion:
          mask:
            - 0.715,0.015,0.716,0.053,0.979,0.05,0.979,0.01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - name: frigate
          image: "ghcr.io/blakeblackshear/frigate:stable"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8971
              protocol: TCP
            - name: http-services
              containerPort: 5000
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http-services
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http-services
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          env:
          volumeMounts:
            - name: configmap
              mountPath: /config/config.yml
              subPath: config.yml
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
          resources: {}
      volumes:
        - name: configmap
          configMap:
            name: frigate
        - name: config
          persistentVolumeClaim:
            claimName: pvc-iscsi-frigate-config
        - name: media
          persistentVolumeClaim:
            claimName: pvc-nfs-frigate-media
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  selector:
    app: frigate
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8971
      protocol: TCP
      targetPort: http
    - name: http-services
      port: 5000
      protocol: TCP
      targetPort: http-services
    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
    - name: webrtc-tcp
      protocol: TCP
      port: 8555
      targetPort: webrtc-tcp
    - name: webrtc-udp
      protocol: UDP
      port: 8555
      targetPort: webrtc-udp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  ingressClassName: nginx-private
  rules:
    - host: frigate.lan.theautomation.nl
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frigate
                port:
                  name: http
  tls:
    - hosts:
        - "frigate.lan.theautomation.nl"
      secretName: tls-wildcard-lan-theautomation-nl
