apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- includeSelectors: true
  pairs:
    storage: truenas

namespace: tools

images:
- name: ghcr.io/x-real-ip/radicale
  newTag: 0b8aa17e111416bfc537cdfd01ff90a5b0c5c72e
