apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- includeSelectors: true
  pairs:
    storage: truenas

namespace: tools

images:
- name: ghcr.io/x-real-ip/radicale
  newTag: 2ebf3f68bffd984a65e78a8664350147480d67cb
