apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: 360f428a1e5512637b9e6bc011706aa204a82429

namespace: home-automation

commonLabels:
  storage: truenas
