apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: 1bab76688b11ffd5c563a634555f7580e70eabc1

namespace: home-automation

commonLabels:
  storage: truenas
