apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: a58a1a3d6625c7e94dbbf2a02e7cd4b42e0add75

namespace: home-automation

commonLabels:
  storage: truenas
