---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx-private
nameSuffix: "-private"

resources:
  - ../../base
  - configmap.yaml

patchesStrategicMerge:
  - patch.yaml

replicas:
  - name: ingress-nginx-controller
    count: 2
