apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx-private
nameSuffix: -private

resources:
  - ../../base
  - configmap.yaml

replicas:
  - count: 2
    name: ingress-nginx-controller
patches:
  - path: patch_deployment_ingress-nginx-controller.yaml
  - path: patch_ingressclass_nginx.yaml
  - path: patch_job_ingress-nginx-admission-create.yaml
  - path: patch_job_ingress-nginx-admission-patch.yaml
  - path: patch_service_ingress-nginx-controller.yaml
