---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: controller
          args:
            - /nginx-ingress-controller
            - --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller-private
            - --election-id=ingress-nginx-leader
            - --controller-class=k8s.io/ingress-nginx-private
            - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller-private
            - --validating-webhook=:8443
            - --validating-webhook-certificate=/usr/local/certificates/cert
            - --validating-webhook-key=/usr/local/certificates/key
            - --enable-metrics=false
            - --ingress-class=nginx-private
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services-private
            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services-private
      volumes:
        - name: webhook-cert
          secret:
            secretName: ingress-nginx-admission-private

---
kind: Job
apiVersion: batch/v1
metadata:
  name: ingress-nginx-admission-create
  namespace: ingress-nginx
spec:
  template:
    metadata:
      name: ingress-nginx-admission-create
    spec:
      containers:
        - name: create
          args:
            - create
            - --host=ingress-nginx-controller-admission-private,ingress-nginx-controller-admission-private.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=ingress-nginx-admission-private
      serviceAccountName: ingress-nginx-admission-private

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-nginx-admission-patch
  namespace: ingress-nginx
spec:
  template:
    metadata:
      name: ingress-nginx-admission-patch
    spec:
      containers:
        - name: patch
          args:
            - patch
            - --webhook-name=ingress-nginx-admission-private
            - --namespace=$(POD_NAMESPACE)
            - --patch-mutating=false
            - --secret-name=ingress-nginx-admission-private
            - --patch-failure-policy=Fail

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    metallb.universe.tf/address-pool: private-lan-ips
spec:
  ports:
    - name: home-assistant-coiot
      port: 5683
      targetPort: 5683
      protocol: UDP
    - name: mediamtx-service-tcp
      port: 8554
      targetPort: 8554
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx-private
