---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.33.33.100
spec:
  ports:
    - name: home-assistant-coiot
      port: 5683
      targetPort: 5683
      protocol: UDP
    - name: go2rtc-service
      port: 8554
      targetPort: 8554
      protocol: TCP
    - name: mosquitto
      port: 1883
      targetPort: 1883
      protocol: TCP
