kind: Job
apiVersion: batch/v1
metadata:
  name: ingress-nginx-admission-create
  namespace: ingress-nginx
spec:
  template:
    metadata:
      name: ingress-nginx-admission-create
    spec:
      containers:
        - name: create
          args:
            - create
            - --host=ingress-nginx-controller-admission-private,ingress-nginx-controller-admission-private.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=ingress-nginx-admission-private
      serviceAccountName: ingress-nginx-admission-private
