---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    metallb.universe.tf/address-pool: private-lan-ips
spec:
  ports:
    - name: home-assistant-coiot
      port: 5683
      targetPort: 5683
      protocol: UDP
    - name: go2rtc-service
      port: 8554
      targetPort: 8554
      protocol: TCP
