---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-api-key-secret
  namespace: deeptutor
spec:
  encryptedData:
    api-token: AgBvCYw3FswUr4ERmJxAItwx4se2lCTI8oqCAlcDHjNXwZZeVCuRhY46OFCaDQ52sPWLxtBxv0pmfmmEW1raX/W2UJldJWXxOBIyhzqv1E8gP8cgBl1AODh5qX5SrTWdbNLp+JUOc9o3MAfb4hMAyQwmypId6nSXpNyMbpjV0ztsfRMtHGgGuZNfy95N1ii6W8tA9SB7A84lDgMz58BxH3bUZs38mR7oE3EhLJ6pBezoVvZAKKViSGRS6W20t7r2o8DySzx0z8WJiLchvY1THA5VcKQZY5IhFHk/8tr+9RzH0cB1eUkTGdQMXZqFaCfBHTkEQCfDequ067cxPms1/E7x9GUTj1VuYZMtyEeLL8xwbmz1Af/0BCntL8p4Sl6LEJNRlLzCIU8rA0SnbuWGeRRSzWuluNITTIpCJzo12WukMDqR6sMHXc6/dESevX+8iWsN78Bjxs5EKpNajuYTuLILM/Sb7YLd/BwAHLSK4nB2fufCZP6vzeOrCrxbug/jhT+3BPZ+7CXKoNryD5wU76v8LO+Vbv/AJmHQBwGQZ3c0ctSLexmua0WSIqCVGmIs2JovN8xHQbOHPoMQSIvFS+ix4BZDJiCvF0z8LaUuZWf4zqq8akHcxZ0mTkdJFHdZcFzQK7Oxt7K53oKfXCB9sa3AXEEKKnd1seA9I47sktJJTXjHaaLU+AKLZ9zX19Da/yc0/0Wet3ZzXmA8U5l99OKiTOPlia1HrDn57qMs5uvfI4EtOmjH+1VL9WHK3gRorJ8SXcLE+hQJxE4L51Ct6dLxI1f5uaSXbqMjlGD822343iaXcg2J4B4NNxvt/7TgK1nEVJEzjb6ebFg3/9Wf4FJ4Gi6fJb9yrG5wWsKG26zh3/szkfNYViN3U4FV5P6iRp1q80xlXVUE3qi2rvL054KMxpqtzA==
  template:
    metadata:
      creationTimestamp: null
      name: openai-api-key-secret
      namespace: deeptutor
