---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx-public
nameSuffix: "-public"

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

replicas:
  - name: ingress-nginx-controller
    count: 2
