---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-nginx-admission-create
  namespace: ingress-nginx
spec:
  template:
    metadata:
      name: ingress-nginx-admission-create
    spec:
      containers:
        - name: create
          args:
            - create
            - --host=ingress-nginx-controller-admission-public,ingress-nginx-controller-admission-public.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=ingress-nginx-admission
