---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-navidrome-config
  labels:
    app: navidrome
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-navidrome-config
    volumeAttributes:
      portal: truenas-master.lan.theautomation.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:navidrome-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-navidrome-music
  labels:
    app: navidrome
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-navidrome-music
    volumeAttributes:
      server: truenas-master.lan.theautomation.nl
      share: /mnt/hdd/music
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-navidrome-config
  labels:
    app: navidrome
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-iscsi-navidrome-config

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-navidrome-music
  labels:
    app: navidrome
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-nfs-navidrome-music

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: navidrome-secrets-env
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    ND_LASTFM_APIKEY: AgCjNraTEgAIJWVqGtKXYgrd1nPpNnngQrZGVpvRMGuY4Zl2uFSXNiBF1l5qDGli6Xxypg+VePG00vNjFrPAuoA54rX+BvIgeIUiym70EGRP1u6oWm+n1PXkUm58FrbhQR3ITtJ6WxTtpPXJb2kfaxp4m6DvzLZgpl4bK8AzaKUgv0sjHViGVJIFYhpcsFpkO1qEUqBcSCaB55pwdPom8YtJvkhtdz2CKmA8ZyK7c3oHcg5BL1EWWJ30qEez3dtImhnRHK0wMBrRw8/pL9WUfEGxqJ7idBmmZYcDWjq8bb+6wqW0zmSMFS6akaB4NcrnVz1ANiCSuJWJikD/e1Q5O0pnGVuy4ss1yFyLQ59QrqCKfSHrZ4AXY0rygO66p2Wlplq1Zvs8bfuKLaUDT3ENXbwHySwm+Jx/SniZcsLl3H9+OhMXVurb19fS5sDe4DrHiKYhldWWjkPPRyEMOeG+wCiNmyquSfuOmpJPJtYaFsiATX0vsXURsJ/uSl7vqMIyF5iuB0juVXG8m8AGbdy9UKgbkdoiIuv24UPMOE1FDP1auhZtedIJAkUP2lhIY2y5g5mdg9mqPGhXIYcho+49cld5tEYlEzka3vfpDLd1469NQJt6tY1a0nVFFBgBulYJohNkO4CqImW0heCelLSUWy/k1ITeza/bcNWAGE+iVS6Zag24tuSUPk9Bo5OR2vMxBlRaSgokcpb/ngHsOp1qRClAO9TO1y3cVme/6PEysbm7aQ==
    ND_LASTFM_SECRET: AgAyRJNO3CuhgzDdHd4IknvO9ex0q7B1kddeCZfxi5+m3rqFRMUP0+D5it8gw0l2XdAvmkgj7UPKRLfEWP28IcqD5216G13zBxv/gGaHk7RZ1Xs/ngOHUDTFVgEPolt28bVdnirZLuawd790m4mzYqmLhkZ11R27rePPyIPUxnvgguKVgbMxR5A09TmlmHjqpnrh3RNloQuaaICw1BDipu7UXgHfMLL5Hdrr66VlSJjzJMYvt3RciGfqCu83jbgonokIUM96SycYA5lM47rELtN2F4NYA9FSuJOVnoEsCQ0Eep/eFnHlF6ccA7kNtFRobiCULkarmO66V9ZxgpdSR6JY7/Cz5LTLUVPRClg6KSrJhNS2VKzl9m4klJ8ksD+ZAxVKq0VJUGNcSnKSL7ALpYiUT78UxhK7gkShhi9WTPmgwT/XcZf9eg6snNV1W3l+3FVosJjX+pMWDFPwlWCFLNDuCahV6Dj2Yl4zAiAY45tsA0CAhnMDRmvL9Jd+yz9MLPiPvInESyiLtuSCqlFOB+hvH/KWB2s48FQIKXs+LxXab8GyUUc4CXdTdvri9Y1i+lFtCm8jI4JUvV2dlx4MLyqXoAaw77Nk+b8jlxJfBKKFXVihXYWz8NwvqIkqzLx2MVlNktsJgAsA93jb8y1E0StavMJT6mV2dYaDragX/viYtbsO/4kS0rgEUBFwayYpLAwBVn7teDT/OHzDW/wklI5AIUIdnrN+MzQ+3oyHvZ15nQ==
    ND_SPOTIFY_ID: AgCMHqlPDGcHVmxfxnZv30EIjtw8JQEf0OsJ0/xr27VkAUPBi4Z/71S0g3prEYQMUCi57rn4DDazerkrO2U2CpC4MLZydKsU+zsmOmKDgLSzybGmfyUrArVZRa26DaxG3M/mDSwkezXWKFNTtST0SLw0gQHnNrA+mvSo2zpXWTl2FrSFWSVE7u9KZ/+98S0BrATsfYz7FCNb9FPqQu5iqChO592TPoMG20IWa6piniPQZwKDJmC/3XyrihXB48NYQif+PPXU5REb1BD5z0xRhhLwVCIBUd6dMkUMsqLby10WvdIT+J9QLL2XB/uVjOkwvv5XVf/A9z6aA/mAgIAkzTmW//PGMeq5wP4/GEondKlRFA4RaqpWA3k0S8Xr934DnqYSbW4DZPLj9XPiseFpJcnvUvY6teae1l80u/vvO3PSLr9M3VlzUbvpVdq2RNP06oV26CSeDoYetGZzPVDRRQPYQwLA+g4K2lT3l0g4OkN0vx6nJgR5gJGcwOAlii8yHyKXbms1BvSmL73jiLWH5R4qv/jcCgzg9MA82aDBBnFApBMSZyGKV+qzwGSYxHtKc7pMT8Raalj9pDaFnHeaPAo5Ft4BSxpR2DcFJetAh76VYwLlW8ytxm5DZPnsUzpUNHHaPSUR3jJMiAMBSgS3mj/3lfv/KvlR7/FgkW3rbrfmP6ZSI57ZRCZ5J5EGPWYizqLmKLQGZbWfTYVeFJlCtPKtxQClo82kv4cmh26LIFCo3w==
    ND_SPOTIFY_SECRET: AgB/55peXPTF2UihGmdiGSeP6E3lUb/TUdBNaFBYDRa8yOI9CLm2wL0tp+DxWdPwgadJuxnZt03svW7TRCprprmbvlD+Vvcb/1UGzgv8hMps2VwkYGo27tWDhVo5rZ7Pf9sfctmI9EYmUhvk+FeYDo+5Mka/LmUfY+J/HuHupOk2ar8NOqTeZMIe+Tj0OV4U/8EKrhJSMo9ni5QWXE+g558LPfDWSU5Gu6JT8dVOUotyeGnEESal8HJSHTSDcANRF2igwpqYLLJ5HbM4UKvFdGnJjjTSOdCszg1dYfXan1KqGNvNIauRaUsPfulnis5yazPjceTjIm83JflhS6G5FFG4NWeVMynxmOzpDx9kloX44mA6LNmXM/l9IwghB4q1g27dolmSErn1Yb9GuEaxaLYiQ59SL1PAflcmmJQbyPlS7RXC9Sz5f94yDiePJkEPXyyqIINtETdsh8mFpOB/hvp8OuCmClWI8PtDgGFGWcFsmw3UMUdLQLy3Y1bk/2sIGarMoNqbltcpJwrv80bxSWihEfmEzV7mXrtNt+bOfsUGWNvRcC3oq5IbZx5DbU2EHjE1OKKA9l80S2mrp8FWIZRSuFCXoDjKfiUTA9W8apcE/oJMGCazrlwLzYv7ZgXyGIBazewzGVnchQ/O4xKM0965dvg9/iTUE3xWSL6W4RnJxmj7ZMsPxH+4+48krBJ0zOSoxqDq/IBywecGOWXty5oI9wgDTQIu8psHRWrGN/H1Qw==
  template:
    type: Opaque
    metadata:
      name: navidrome-secrets-env
      labels:
        app: navidrome
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: navidrome-env
  labels:
    app: navidrome
data:
  ND_SCANSCHEDULE: "@every 1m"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_BASEURL: ""
  ND_LASTFM_ENABLED: "true"
  ND_LASTFM_LANGUAGE: "nl"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          ports:
            - name: http
              containerPort: 4533
          envFrom:
            - configMapRef:
                name: navidrome-env
                optional: true
            - secretRef:
                name: navidrome-secrets-env
                optional: true
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: music-volume
              mountPath: /music/organized
              subPath: organized
              readOnly: true
          resources: {}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-iscsi-navidrome-config
        - name: music-volume
          persistentVolumeClaim:
            claimName: pvc-nfs-navidrome-music

---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  selector:
    app: navidrome
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: navidrome-private
  labels:
    app: navidrome
spec:
  ingressClassName: nginx-private
  rules:
    - host: music.lan.theautomation.nl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  name: http
  tls:
    - hosts:
        - music.lan.theautomation.nl
      secretName: tls-wildcard-lan-theautomation-nl

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: navidrome-public
  labels:
    app: navidrome
spec:
  ingressClassName: nginx-public
  rules:
    - host: music.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  name: http
  tls:
    - hosts:
        - music.stamx.nl
      secretName: tls-wildcard-stamx-nl
