---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: alexxit/go2rtc
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: go2rtc
