apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation
commonLabels:
  app: go2rtc

images:
  - name: "alexxit/go2rtc"
    newTag: "latest"
