---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-music-assistant-server-config
  labels:
    app: music-assistant-server
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-music-assistant-server-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:music-assistant-server-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-music-assistant-server-music
  labels:
    app: music-assistant-server
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-music-assistant-server-music
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/hdd/music
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-music-assistant-server-config
  labels:
    app: music-assistant-server
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-music-assistant-server-config

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-music-assistant-server-music
  labels:
    app: music-assistant-server
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-nfs-music-assistant-server-music

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant-server
  labels:
    app: music-assistant-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant-server
  template:
    metadata:
      labels:
        app: music-assistant-server
    spec:
      containers:
        - name: music-assistant-server
          image: ghcr.io/music-assistant/server:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - DAC_READ_SEARCH
            seccompProfile:
              type: Unconfined
          env:
            - name: LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music/organized
              subPath: organized
          ports:
            - name: http
              protocol: TCP
              containerPort: 8095
            - name: stream
              protocol: TCP
              containerPort: 8098
          resources: {}
      hostNetwork: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-iscsi-music-assistant-server-config
        - name: music
          persistentVolumeClaim:
            claimName: pvc-nfs-music-assistant-server-music

---
apiVersion: v1
kind: Service
metadata:
  name: music-assistant-server-service
spec:
  type: ClusterIP
  selector:
    app: music-assistant-server
  ports:
    - name: http
      protocol: TCP
      port: 8095
      targetPort: http
    - name: stream
      protocol: TCP
      port: 8098
      targetPort: stream

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: music-assistant-server
  labels:
    app: music-assistant-server
spec:
  ingressClassName: nginx-private
  rules:
    - host: music-assistant.lan.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-assistant-server-service
                port:
                  name: http
