---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant-server
  labels:
    app: music-assistant-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant-server
  template:
    metadata:
      labels:
        app: music-assistant-server
    spec:
      containers:
        - name: music-assistant-server
          image: ghcr.io/music-assistant/server:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - DAC_READ_SEARCH
            seccompProfile:
              type: Unconfined
          env:
            - name: LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: music-assistant-data
              mountPath: /data
          ports:
            - name: http
              protocol: TCP
              containerPort: 8095
            - name: stream
              protocol: TCP
              containerPort: 8097
          resources: {}
      volumes:
        - name: music-assistant-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: music-assistant-server-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.100.244
  externalTrafficPolicy: Local
  selector:
    app: music-assistant-server
  ports:
    - name: http
      protocol: TCP
      port: 8095
      targetPort: http
    - name: stream
      protocol: TCP
      port: 8097
      targetPort: stream
