---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
data:
  default-setting.yaml: |-
    priority-class: longhorn-critical
    default-replica-count: 2
    create-default-disk-labeled-nodes: true
