---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgC5/zAbe501srdQBevssRDz05z5ZWSiuIVZyqZKOh9sTlFXJ5jAsvrrT0s3jfg82EevPmaBv9nik8p674n1SIP483fSWsm2YbsgAADJ4xRotOKkzUBmX0mwE7wpRwm5djJzJwlMsxBb4PgjkPdF01np3C8fOENq0+qJvUEnqXJ+0178ZI2g1mDOZ5UChFc6eaxpE7oX25rEWtET70STcwUmbYw/f22RxzWFVEg0qkl+93fEryRHdNR3GONg/NaCaMYtIhuSSVGtpiagMA+XR3kI5Cp4jfKMwxsGtg+1v2RLQ1ipegmswUOWs+V5ymTShzbmQmIxsVb/Taa7l8PkF8uYexH8KDADtjUDzWNUacHVZo8+7cy2cBAhjOdD8494TN+A/3vK4yli56h7Xnvl7WDZzqnWREdJlm2dkbAwa2Bu7aqSXxNRGu/5PThqkofJ8DTdJP4um3IBMuzY0wzfd7Ljl1Qu8KgcybY9c190OqS50t0ANTLOHTSlR1AcmMVazb8mg6/M14Ep6LUHOWmt71hUK4ylo8oVZKKsYgVeFBwpQztzmn678FTausKbXgPa3GHgA3oFzeTHTSA1HVU/eiwEE7Pho15pWLQqArZJ1363DV7BuLzPEfnv7RIFjVEroKFRRLrWwz1Lu+Z0ET5c1hYhy+wzVHD1hBnZYrLvaj+MUSquAnoEc+l5ghdT5F5A6GTuLfUbuWipKwM5IlHIIZ/myEyXEvJO0sDofVbyStOIV+/IF98x4HX3QwFe
  template:
    metadata:
      name: basic-auth
      namespace: longhorn-system
    type: Opaque
