---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation

images:
  - name: ghcr.io/xirixiz/dsmr-reader-docker
    newTag: 5.11.0-2025.01.03

labels:
- includeSelectors: true
  pairs:
    storage: truenas
