---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: tools

labels:
- includeSelectors: true
  pairs:
    app: cups
    storage: truenas

patches:
  - path: patch_deployment_cups.yaml
