---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cups
spec:
  template:
    spec:
      tolerations:
        - key: "machine_type"
          operator: "Equal"
          value: "odroid"
          effect: "NoSchedule"
