---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-node-red-data
  labels:
    app: node-red
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-node-red-data
    volumeAttributes:
      server: truenas-master.lan.theautomation.nl
      share: /mnt/ssd/containers/k8s/node-red-data
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-node-red-data
  labels:
    app: node-red
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-nfs-node-red-data

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: node-red-credential-secret
spec:
  encryptedData:
    NODE_RED_CREDENTIAL_SECRET: AgCJhVDJkHjyzh726+XT9FSrbXRx+y/cjJSELBqiLce4ElSNP661iZs+sca9iVo6ajgLKSImA5JKOTpeprKO2iqljrf3nDjz8WHo5Xx88nTHOgrmLWWcegS3l+VPkt5tDdW0sgZi/Xnpb6qKO7lgIulz0oTg+qNkju1M37j7wyiHNIadY+m0p8ZZUY9Pb9Auzx54YihNyUbX3T87+1ia1IMJ/6H4Fbm9Z5HFXQt1TZv1sUxnIILAt5PB/cDXd/foyGUdfYoaoFgPkdKUpD1u/Ck+6zuP2DlfVInfepmReEu4fXevhW1KvsJFMLK/KUtaiV9nuS9ac+wrB5Zlzs50QiMUQM+Iwcy8Wfg01it9EJZ2T56+MHfg2RDRYVzF26YZAkfdRC/+WWxhO5qRZuobbcAK51ceAY0s7e17wifCk/LeFEQF3xDzbLEGVv7mKBqEN+/5YWYps3aufsuhmJDwdVM9Puv9TA2+8IM5M4/+RTjdlKRKqUhoTxe5N3Kb9BtBO7FCw2WjGgnyd+iiw3uSyaoE5VeCOSGGIj0EQ6xDXQdgH1LyCS2yZw4aNTlLMxZml3/A5Oo9/3liM4ls2MdGakXZuMqv5so3q4vGgWT3ata99Px/GeW2mWwIhSZCIxjDEL7Hl7LlAUWvOeYmRGeQ1KDD13Qxo1n2dO/TlJyOaE8tp7zTeHjpDvKLN0bYJi/mO3vd/Ayb50oZClc+AnRXWQdnXobjde949A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        app: node-red
      name: node-red-credential-secret
    type: Opaque

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: spotify-api-credentials
  labels:
    app: node-red
spec:
  encryptedData:
    SPOTIFY_API_CLIENT_ID: AgDEUeoaWFdyR760gPnYU5zFE2T0SGPwu0VRb/EHyFs+XlJvgvmeaq2BEhrlF04310NukPsvtaYg0cCcYRF3AFsWkMuIcXZ5XJs3Lj3C/xOuiEa5DhKzedRom/umMcJDJxokY9Zs+Clk0/A3Yy9f3FHqV5pQUxwFoENAzfphv380aZMxlzp1EB+IzrC5qdEa0LjhRNMdzxXhMmHVaFD0UcUijbIlCyMV22SS3t/o7HX/pWdXI9HkLhi1L/3v3ieW2dtjCylW6/6DnNy8yixqiwCjvXqKFZscCPKGQZy7YSuuSpA3SzUM7yoCqiDq1m8VsydyWQZI98oUEEExi7C7ILHrwXpwvUhoOEmeuWCX+84a3PaVxmOX4k37lYw0bvUUmmi6Xi+p4pz0K/ebG/+wYOlfyyPbPi6i5fP/4V3VmBshzXEwqSAPV9m/beVd2qMNA44OA1eSjzPWw2gkJwpJhoAwfXYyy/nktxUyaLepfaZ4MHI2uDvr8zAEwvZ35zsNRNm5xVoOCWyEN/Ck0M8nOct8O0XWnKESidqmGx8BDo64Jb2/7NX8+MZduBR9IBkbLyskwKhUwrnX6roWhT7Mi9SRcw21XMCIWsDlTPobG1GTQOhllZC5fS6SzUtyX6ajPU/SZDBzrvt/u1A0v071SOtmMOet59RCyoW2CVDMqonpVlCAppLVEE+sl2jDODxU6wc8GV/IK+ct/GVwKI/TZ0OqiNVf5ifVuzbsMZAdmj65Mw==
    SPOTIFY_API_CLIENT_SECRET: AgA8Oxhk31tEI3wnkWhaY5LuY1v2FL/gkt2udQ3eBzJATukf67bWlJlop3UyF/duZf6AgjZur3ev/hDESi6B7/hs+BHbUbtfKjfSBs1s3KdjOByN/UkhA+48OkEIvbuO5jHKkASMsScA2Kw30vvwr3MR4q7UskR2aEITedoJ/bdGgXTCHA0IFbj2OvUN8fgv3YPcaYmRLb3YAq6eZyQIwotIGWeRaMXWfZ2dOS9T3Rd/IASkEfKwToANMfjXES5lkRTByrHwzbi/SAhLiGLG2dAgvuDsZjVpigga4SynB/sgCeAAXrlBUcFTQTYlLnoE+u8kRtDVLg8dzkuCE8FBdjeTVnIiLHe2tbkULe9LM9Q/1WR3xq7k7eU7FvIX06Lv97/dm8Jk/OOOY5nmZC8vWcuAWJ6BZ4SaJfJ2kc6cyIrX/uP5DVPoXRgZCNrPUCrRtAzhe2jX8VyWQAK1xDvQf0qdMOPE4KOsjgaT/jlilAaLouOVFka3khPt7tTzz9sFOAbAaukLHsFdmLoatmWnnw9yVj7cCZWQCay88H3lTd3riu6VXKq58TnTC6t8Dmuqx4TQDAuJazRQKP/fbTffKaBq/QfwVod7zEFZOkSKIqEngs01hHoOhu1AHjctiOEnityzcVSsa9rxDM/MV0aPzJnMiLXpgKsHdLqZjiWC2N9FqjrNl73DWx9E2OytEjCJTGWgtyHYLlqcSpsV3TnDati+zDg2NfsR05XZ2kzf6z69/w==
  template:
    metadata:
      labels:
        app: node-red
      name: spotify-api-credentials
    type: Opaque

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: node-red
          image: "ghcr.io/x-real-ip/node-red:latest"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          resources: {}
          ports:
            - containerPort: 1880
              protocol: TCP
          envFrom:
            - secretRef:
                name: spotify-api-credentials
                optional: true
            - secretRef:
                name: node-red-credential-secret
                optional: false
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PGID
              value: "2000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: node-red-data
              mountPath: /data
      volumes:
        - name: node-red-data
          persistentVolumeClaim:
            claimName: pvc-nfs-node-red-data
      imagePullSecrets:
        - name: github-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: node-red
  labels:
    app: node-red
spec:
  selector:
    app: node-red
  type: ClusterIP
  ports:
    - port: 1880
      protocol: TCP
      targetPort: 1880
  sessionAffinity: None

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: node-red
  labels:
    app: node-red
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx-private
  rules:
    - host: node-red.lan.stamx.nl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: node-red
                port:
                  number: 1880
