apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: ghcr.io/x-real-ip/webdav
  newTag: 6c25a492f6d56d2d06811fa23fc36d97f755749e
