apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: ghcr.io/x-real-ip/webdav
  newTag: 69a8ca77eca782a23ac44379341d7ec1c756319e
