apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: tools

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: ghcr.io/x-real-ip/webdav
  newTag: 4cf91502413bd8072784fff10f719d9f1bfa63f5
