apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: tools

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: ghcr.io/x-real-ip/webdav
  newTag: 219cc39d1d880781682ea94f0f858cbf0349caf0
