apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation

commonLabels:
  storage: truenas

images:
  - name: "ghcr.io/blakeblackshear/frigate"
    newTag: "latest"
