apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: ghcr.io/blakeblackshear/frigate
  newTag: 0.15.0-standard-arm64
- name: ghcr.io/x-real-ip/frigate
  newTag: bace91c028304ea07ca89f4c5fb7617202a38212

patches:
- path: patch_deployment_frigate.yaml
