---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  template:
    spec:
      tolerations:
        - key: "machine_type"
          operator: "Equal"
          value: "odroid"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "feature.node.kubernetes.io/usb-ff_18d1_9302.present"
                    operator: "In"
                    values:
                      - "true"
              - matchExpressions:
                  - key: "feature.node.kubernetes.io/usb-fe_1a6e_089a.present"
                    operator: "In"
                    values:
                      - "true"
