---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  template:
    spec:
      tolerations:
        - key: "machine_type"
          operator: "Equal"
          value: "odroid"
          effect: "NoSchedule"
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_18d1_9302.present: "true"
