---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.101.0
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.101.0
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.101.0
  