---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

labels:
  - includeSelectors: true
    pairs:
      storage: truenas

images:
  - name: docker.io/mbentley/omada-controller
    newTag: "5.13"
