apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/esphome
  newTag: 7112cb18781fef423434f93347c7c505e5aed486
