apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/esphome
  newTag: 5d125f4d749dade5f887d47caf2a356636da3168
