apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: tools

images:
- name: ghcr.io/theautomation/grafana
  newTag: 1305c33c956d510fec2b501c214d02eba5566ae3
