apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: home-automation

images:
  - name: docker.io/eclipse-mosquitto
    newTag: latest

commonLabels:
  storage: truenas
