---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-core-apps
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: ""
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/core-apps/
    repoURL: "https://github.com/jetri/gitops"
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: false