---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-datasources-secret
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBZpSKvwtEzDzQ/JZMOBfCHlmG/9p4c8zz+vMQJVW1l51u+K+Biyk9BAF7DIHcJjc6T8MmgYUdnUeplsQKunyJt3QpXHfAIU5SihaGY0sMJ1kF+W1KfegsDpZnX1DUQRCc/nGZ5k2WhsuKVxPRlu+knYGQH0XF5D0lryeR6ZYIRIVueEZeFDcQxAeyrYTlndC4FY7e1CxeK1WU5cVfa9+bO8zSHghbfYP7sNT0XmXPiSlAOJZ071Y5ulZkL0x11Zzu//LCj+2f1IHgMFlgdJOYyAexQbH3828DORGhH/Aa4gf4rD6/M0UmYbq9DBMfIE1D7YJMEZ7ugb655fAIcg9FOhmLFCh4BXANYvOj6qIJQAwOIfLVRU0oDIKaDXhH78ZJuSSlxD1aMepuzmYfuN8jsDfW/IC8c8IE6eCOc/zhr2Bzn7PNPTtN/wlb0h4c0AWy30Nx23Xn9p76QIhUjZN+/mSyVhIBLhJVSsXjD5joKUDee6LSabOG1EPtZkJJsw/kiwAyRzflFEY6TPWZ/Dvsz+svMIlW3lTnC3V5hcCVCW+tJbKQPXGSuyZLMKwUPFqezwR4ClLyPUHItT9d+bt64nZfnpRZiaeEus13MQxd9sQplUZP1vKdhACmryf/tkcKY3SKb2wYtMVVQ0VrRgpbmqWx21/AgwtrmahRFBnv0p8r+uOwmNttQFo+BNILD+yTGbEd3rgWZ3z61HE+hGwuHGYeYFt2XKLNNO/+zhpefvqkdOn4A+Q==
    GF_SECURITY_ADMIN_USER: AgAaVvK/+Xww2Tj2cmnp3CEEVsKx1lTnanh04vgqdWXujnfsCHGpa93Zj4Zv4bx3dHpUW0g0Jt9sEFayKoHqRNMSP+dWw3Uvd7gMlBoIi845UjGXnW4T4NMGekFnKiJXVsolbTg0dpAxWQyHKe9LDhIOFro5gfTgX0/E8Po28J7VWOTZNKnfeUHtrEYA/7ZsbL0d+ZzTcHD8yrw5Sog5yS3gYr2ML4kSVpCyFCg25yUuk32zSC/hTYTANZgAI9bBkIHFZ+TkJ7nwHJuYeC5LDtPSMU0Z2biJiamCdcqWI7RnsfaEJc4ms0jGXb6FPF5mljlAt/qPM6X2Sv0f6QA7gnL+GzSesEkggzRok3RzlyaPKCrkCxg9oOzfSfvh2wnGmoiEcKPsQ23oH+W2wd3N6xQlpDmBQwEcAw+Ifsydhl6KPbdcWlum9N56emlk1Ygd+Cu1hF5hzp2lJPg6KbUgrTSkOf8qWmKBiNFIvZXrNy+7SfoRT9rCbe5j4dxLfHTNE5/Gs4/9puiPoKn/2gZ9s8inDt1UYAUnM+k9JWcUVM/RSpJHQRou2vhhol6jlA9OCZsO0VF+h+US47o03jz0v0buFjShUsWBNV4Ruq9NbFDZ1oq8zPX2B+nIgabsoMHqk19crOyzgS+XJCIcVmZhscRF/N2cIPXo0+0z76KbmThJ17tFq9w8H/WoQxbPGh3jJaY05s9D
    POSTGRESS_HOME_ASSISTANT_PASSWORD: AgCLluRqviBDBF4QjqliKWrnPiJjFTcwVvugXtvW/8aLqYSt+ROCZ6EWM9T5+ZFT68iW4a/a2pyNbwVyQuofqB7TjEywHrAuOYpR2rxb/QhXnmMKP1ZcGnyRsyG13UTF3FRQG6/Ee51eBeIrWJyDWFXdyAZ/l3HxO1iIL9h8vfV8rM6dokvi8T4JKJu4aOYpACJL0J/0n8A2zPFnT5Z/pNaBiVIwYg/3gxxd0hvOIwzPyn1qSe32Lpul4hrSpz4BncgSKcylVrqB/fg2xAaUafBa33edBdffAKB1QeDMfsUQh1QonT6i8BZLUMNji4moVU1y+1VA7Sfbq5ryd6AN7ARnU+1Jw2nTpqeLppEEBjT3Y3SRuZ3qLo25yHFORS8HYBBp7hO7tbFb4t/uE035z9tvLHQhiRR2nQdcbLp45uP+7yPcZU3BSJsd8j14OTGNyLnt7wLbSYYkhKGsvPtOql7GPPhfDu92rJbvhhc0zU2t4F1YSSU9+agrW1hELileyhkZRUfqC8+D41IofFHzZpCRHBsQ+8j+djjTtYbTLMW7YYf1J1xPfmOKd6lsMAlWcB2anMHoapyEF2D7/Npvl+7gFlqAKoA6GWGhB0Jg5TsexPLJSdL/HNGgfJ5mLf2xNT0ha+XQKSfW+U0k+yHf9+dor8AsObYyN5XV36C/M58H6/8d/TYkN/66Hbyuteg9V0N1Z8Vw9c3xFe4MiSvCGSxW4tJjUyll
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-datasources-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: ghcr.io/theautomation/grafana:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: grafana-datasources-secret
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits: {}

---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ingressClassName: nginx-private
  rules:
    - host: grafana.lan.theautomation.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
