---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAd91hHxW4tIjLu871zcx6vVHZfe/s8MC3AUGj9e4sWdpkhaXZoi/Ikp4h50Wib3vfER6qVOcCwDYZWO/Fc626vKiJmPOeUAsYZN2fDzmv2chEuG5R+LWCCt0n3yrVxOXvy2B7R5uLEitLMbISXZepJsDWxU6bCVhTnWKIrpYrNOYHWe0TMxeutVJRnNbBbmKJGvsSwV5i3YNCbIBfwB579qIQHi6zU76w1PAgV4VTNXCMOZ6cLHnGZqwAvddnQ7lWCLV/WK73lSVX0HNg1QsESil45nXj7oStT0/2HbtAqjgPZr4eO/Yq4zvlzoY5XRppUUx6+jdWT9IuinC93oVje9ccXxqXh9Axe1hUmHUfURgERR/InAnwgxROT0KOKqBI2W247jmSHTdzTwm1awx8PYdAzzHZgIiKCXzl2A8bcvz5qgY4WyA3LeRrnG0VtfoRG3t05049mSQCz1v/tUnrgiqw1Bsu8vcTimdf/B22HvPPjbYHIzGswWh3Oz7eZ//ScLYWATARIvNoqoZPVcAGnMG1/SIz/7+PFScOtWr1Y/232R+ly70xbbs2Y4NnhpW1FHRVyHhkMpHSrDBHBYCEJN9vFXFT2QoQctAiG09HaKLnWJUZqY/4jh6AaEC/l/iBp1cMy3RkneBmJy34VaG3xL9MZijgLhpfaIr5YXp+xeootSV1yA6dBuKThli0WN4aPO3aCzr4Rqjlx+iaj0ySMr2bmufgNqmy+aUTYa4RccO9cWeIVzVFp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
