apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-wildcard
spec:
  acme:
    email: j3.laserna@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-wildcard-account-key
    solvers:
    - dns01:
        cloudflare:
          email: j3.laserna@protonmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
          - "j3laserna.me"  # Replace with your domain
