---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-webdav-server-data
  labels:
    app: webdav
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-webdav-server-data
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/webdav
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-webdav-server-data
  namespace: tools
  labels:
    app: webdav
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  volumeName: pv-nfs-webdav-server-data

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: htpasswd
spec:
  encryptedData:
    .htpasswd: AgC3iIc+hLchM/L0QO9TAs96A8Vve9iaPZQrRRtERD+UU3VBmpVzNv0kepa/phGLv50Ps1B9pa2axLeB88j75HJQjZ3N0aLnOv1ftK2j9NyrJIwi9uOtV1KWpRR985wQyiurota18ASk5xLIPnf9dvtfvQ3QhF4FQeGbVCHmvYlzvDacsjwVgXUl39koQ81vuUuPYc8vPJIKNps8vjMu9ZRsr3UzMF6gnB/iar4sHPoMit3hFjyxSGf31nn9P5j+lYKXIcm0UHbahKeFsV8XlvDMGD4yL9CvFVSH/lJu1hgyp3c9o2qf33Praa+d7xTagu2gxx7+4PEhpfnSpiFZYK8uXcG6E1MpGJEg3v85zn7YPX9btJoZZfuueTohJ5PNO9hamk1dt3GCUrMyLUZOsaM/dhSJ0qDi97gK4OuOYxzT82wsWHy50d3Hw59fki7yddQck1kGOZ/QSbeteL9c4uZpY7t24Nw5iLpVfWANWVrwFdEaEd+J2Ifg7npxJt0nr/C6Eb+j9nBrAT+bFQ5+gnQOJpJ4B9AEPmLrlikLSUp2gVCvEOFpKpb0CP5xaieRxgf/v/qtRBHp2UIY59Ti7ipEqYxSs7NMRgI79O8Ur7C8kEz4f6ZKUQlNjblc0FUYi8DnPf8LdMkei8hjdID3vqkkW4Njjh1uIbGVMdDJ3kw6nDcuuToHxuiRGn41run/F/1H8RitTpWtD64kP7HeqdjqMvXyi3n2kGsefCd0tTAmHgf5xlkgHo7uIR1Yaa792iVYAQCarbUq8N6IPr9s5KQZm0MofxuYLwIl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: htpasswd

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdav-server
  labels:
    app: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
        - name: webdav-server
          image: ghcr.io/x-real-ip/webdav:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources: {}
          volumeMounts:
            - name: webdav-server-data
              mountPath: /var/www/webdav
              readOnly: false
            - name: webdav-server-db
              mountPath: /usr/local/apache2/var/
              readOnly: false
            - name: htpasswd
              mountPath: /usr/local/apache2/conf/.htpasswd
              subPath: .htpasswd
              readOnly: true
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          #   successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   timeoutSeconds: 3
          #   failureThreshold: 3
          #   successThreshold: 1
      volumes:
        - name: webdav-server-data
          persistentVolumeClaim:
            claimName: pvc-nfs-webdav-server-data
        - name: webdav-server-db
          emptyDir: {}
        - name: htpasswd
          secret:
            secretName: htpasswd

---
kind: Service
apiVersion: v1
metadata:
  name: webdav-server
  labels:
    app: webdav
spec:
  selector:
    app: webdav
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webdav-server
  labels:
    app: webdav
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20480m
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "15"
spec:
  ingressClassName: nginx-private
  rules:
    - host: "webdav.lan.stamx.nl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webdav-server
                port:
                  name: http
  tls:
    - hosts:
        - webdav.lan.stamx.nl
      secretName: tls-wildcard-lan-stamx-nl
