---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-coen
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-coen
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/coen
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-anne
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-anne
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/anne
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-shared
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-shared
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/shared
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-backups
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-backups
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/backups
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-immich-media
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-immich-media
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/k8s/immich-media
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-backup-source-r01-1tb-k8s
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-backup-source-r01-1tb-k8s
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r01_1tb/k8s
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-duplicati-config
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-duplicati-config
    volumeAttributes:
      portal: storage-server-lagg.lan.theautomation.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:duplicati-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-coen
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-coen

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-anne
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-anne

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-shared
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-shared

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-backups
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-backups

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-immich-media
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-immich-media

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-backup-source-r01-1tb-k8s
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: pv-nfs-backup-source-r01-1tb-k8s

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-duplicati-config
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-duplicati-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicati
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: duplicati
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: production
      app.kubernetes.io/part-of: duplicati
  template:
    metadata:
      labels:
        app.kubernetes.io/name: duplicati
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: production
        app.kubernetes.io/part-of: duplicati
    spec:
      containers:
        - name: duplicati
          image: lscr.io/linuxserver/duplicati:latest
          ports:
            - name: http
              containerPort: 8200
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "2000"
            - name: TZ
              value: "Etc/Amsterdam"
            - name: CLI_ARGS
              value: ""
          volumeMounts:
            - name: config
              mountPath: /config
            - name: source-coen
              mountPath: /source/coen
            - name: source-anne
              mountPath: /source/anne
            - name: source-shared
              mountPath: /source/shared
            - name: source-backups
              mountPath: /source/backups
            - name: source-immich-media
              mountPath: /source/immich-media
            - name: source-r01-1tb-k8s
              mountPath: /source/r01-1tb-k8s
          resources: {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-iscsi-duplicati-config
        - name: source-coen
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-coen
        - name: source-anne
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-anne
        - name: source-shared
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-shared
        - name: source-backups
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-backups
        - name: source-immich-media
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-immich-media
        - name: source-r01-1tb-k8s
          persistentVolumeClaim:
            claimName: pvc-nfs-backup-source-r01-1tb-k8s


---
apiVersion: v1
kind: Service
metadata:
  name: duplicati
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  selector:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
  ports:
    - name: http
      protocol: TCP
      port: 8200
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: duplicati
  namespace: tools
  labels:
    app.kubernetes.io/name: duplicati
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: duplicati
spec:
  ingressClassName: nginx-private
  rules:
    - host: duplicati.lan.theautomation.nl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: duplicati
                port:
                  name: http
  tls:
    - hosts:
        - duplicati.lan.theautomation.nl
      secretName: tls-wildcard-lan-theautomation-nl
