---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: patch_deamonset_nfd-worker.yaml

configMapGenerator:
  - files:
      - nfd-worker.conf
    name: nfd-worker-conf
