---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: patch_deamonset_nfd-worker.yaml

configMapGenerator:
  - name: nfd-worker-conf
    behavior: replace
    files:
      - nfd-worker.conf
