---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go2rtc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/x-real-ip/gitops"
    path: manifests/go2rtc/overlay
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
