---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-entertainment
  namespace: argocd
  labels:
    storage: truenas
spec:
  project: default
  source:
    repoURL: "https://github.com/x-real-ip/gitops"
    path: manifests/media-entertainment/overlay
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
