---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zwavejs2mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/theautomation/gitops"
    path: manifests/zwavejs2mqtt/overlay
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
