---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-protonmail-bridge-data
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-protonmail-bridge-data
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r01_1tb/k8s/protonmail-bridge-data
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-protonmail-bridge-data
  namespace: tools
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-nfs-protonmail-bridge-data

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: protonmail-bridge
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      containers:
        - name: protonmail-bridge
          image: "ghcr.io/theautomation/protonmail-bridge:264547db870059df134a8c19d3de768454051ade"
          imagePullPolicy: Always
          command: ["/bin/bash", "/protonmail/entrypoint.sh"]
          resources: {}
          ports:
            - name: smtp
              containerPort: 25
            - name: imap
              containerPort: 143
          volumeMounts:
            - name: protonmail-data
              mountPath: /root
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: pvc-nfs-protonmail-bridge-data
      imagePullSecrets:
        - name: github-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: protonmail-bridge-smtp
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25

---
kind: Service
apiVersion: v1
metadata:
  name: protonmail-bridge-imap
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  type: ClusterIP
  ports:
    - name: imap
      port: 143
      targetPort: 143