---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: tools

images:
  - name: ghcr.io/dani-garcia/vaultwarden
    newTag: 1.33.0-alpine

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
