apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - ../../base/wildcard-certificate.yaml

# No patches needed as namespace transformation is automatically applied
