apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - ../../base/wildcard-certificate.yaml

# The namespace directive above will automatically transform all resources to the media namespace
