---
name: Version Bump

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Application repository name"
        required: true
      registry:
        description: "registry"
        required: true
        default: "ghcr.io"
      image_tag:
        description: "Container image tag"
        required: true
        default: "ghcr.io"

jobs:
  update-manifest:
    name: Update Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Echo Recieved Inputs
        run: |
          echo ${{ github.event.inputs.registry }}
          echo ${{ github.event.inputs.repo_name }}
          echo ${{ github.event.inputs.image_tag }}

      - name: Replace Image Tag
        run: |
          sed -i 's%/${{ github.event.inputs.registry }}/${{ github.event.inputs.repo_name }}:.*%/${{ github.event.inputs.registry }}/${{ github.event.inputs.repo_name }}:${{ github.event.inputs.image_tag }}\"%1' ./manifests/${{ github.event.inputs.repo_name }}/manifest.yaml

      - name: Show Result
        run: |
          cat ./manifests/${{ github.event.inputs.repo_name }}/manifest.yaml
